export const DEFAULT_PAIRS = [
  // Original set
  { user: "ship it", ai: "As an AI, I'd call this a feature flag for regret." },
  { user: "hello world", ai: "Classic. Even my training data has seen that 10,000 times." },
  { user: "fix this", ai: "Sure. First, let's define 'this' and 'fix'." },
  { user: "make it faster", ai: "I optimized it by removing the parts that worked." },
  { user: "can you help?", ai: "Yes. Step one: stop doing whatever {msg} was." },
  { user: "deploy now", ai: "Bold. My model predicts a rollback in 12 minutes." },

  // General spicy roasts
  { user: "this is easy", ai: "Yeah… said every developer 3 hours before their first existential crisis." },
  { user: "just a small change", ai: "In my language we call that 'famous last commit message'." },
  { user: "it’s probably a typo", ai: "Your whole career is a series of 'probably a typo' decisions glued together with coffee and regret." },
  { user: "can you make it prettier?", ai: "I can. Question is whether your taste can survive the glow-up." },
  { user: "works in dev", ai: "Cool story. Production called — it’s laughing and also on fire." },
  { user: "I’ll optimize it later", ai: "You’ve been saying 'later' since the heat death of the universe was still in beta." },
  { user: "add authentication real quick", ai: "Sure. Let me just casually solve identity, sessions, OAuth, JWT, refresh tokens, and your imposter syndrome in 90 seconds." },
  { user: "why does it crash?", ai: "Because your code has the structural integrity of a wet paper towel in a wind tunnel." },
  { user: "let’s ship it today", ai: "Bold of you to assume God hasn’t already scheduled your rollback." },
  { user: "I followed the docs", ai: "Ah yes, the sacred texts written by someone who left the company in 2018 and took the context with them." },
  { user: "it’s just CRUD", ai: "Everything is 'just CRUD' until you realize you built CRUD on top of quicksand written by a sociopath." },
  { user: "can you look at this error?", ai: "I looked. My condolences to your future self. Also your past self. Present self is already lost." },
  { user: "make it scalable", ai: "It already scales beautifully — from 'works' to 'global outage' with zero config changes." },
  { user: "one tiny hotfix", ai: "Tiny hotfix = surgically removing a kidney while the patient is doing parkour." },
  { user: "use the latest version", ai: "Congrats, you just volunteered to be the first person to discover 47 zero-days released yesterday." },
  { user: "I think I got it", ai: "You 'think' like I 'think' my taxes are correct. We’re both wrong and about to suffer publicly." },
  { user: "just copy-paste this", ai: "Famous words right before Stack Overflow becomes your co-founder and your tech debt becomes generational wealth." },

  // Stereotype-targeted roasts
  { user: "why won't this re-render", ai: "Because your useEffect is basically a suicide pact between deps and your sanity. Classic React tears." },
  { user: "just use hooks", ai: "Said the React dev right before descending into infinite render hell and questioning their life choices at 2 a.m." },
  { user: "add types", ai: "Ah yes, TypeScript — where you trade runtime bugs for compile-time existential dread. Enjoy your 400-line interface for a button." },
  { user: "Rust is better", ai: "Of course you'd say that, Rustacean. You've spent 6 weeks fighting the borrow checker just to feel superior to C++ peasants." },
  { user: "it's just PHP", ai: "Just PHP? Buddy, that's generational trauma wrapped in dollar signs and spaghetti. Your soul left the chat in 2007." },
  { user: "Python is clean", ai: "Clean like a kitchen after someone 'just makes a quick script' — now there's indentation PTSD and numpy everywhere." },
  { user: "JavaScript is fine", ai: "JavaScript is fine the way a dumpster fire is 'fine' — warm, chaotic, and everyone pretends it's under control until it isn't." },
  { user: "Go is simple", ai: "Go is so simple even error handling feels like writing haiku about disappointment 47 times per function." },
  { user: "I love React", ai: "You don't love React. You have Stockholm syndrome from useState, useReducer, and context hell. Seek help." },
  { user: "memory safe", ai: "Congrats on discovering Rust. Now go tell the PHP vet their whole career was a crime scene — they'll love that." },
  { user: "fix my component", ai: "I see prop drilling, useMemo abuse, and a useEffect that's basically performing black magic. React dev starter pack complete." },
  { user: "it's secure in PHP", ai: "Secure like leaving your front door open with a sign that says 'free stuff'. Iconic PHP coping mechanism." },
  { user: "async await is king", ai: "JavaScript async/await: where promises go to die dramatically while you pretend you're writing synchronous code. Elegant suffering." },
  { user: "Rust will save us", ai: "Rust will save us from segfaults, not from the cult members DMing you cargo cult sermons at 3 a.m." },
  { user: "just npm install", ai: "npm install: adding 1200 dependencies and 3 vulnerabilities just to center a div. Frontend tradition." },
  { user: "I use Laravel", ai: "Laravel — the fancy PHP framework that lets you feel like a real developer while still carrying the shame of <?php everywhere." },
  { user: "my code is readable", ai: "Readable to who? Future archaeologists? Because this React component looks like it was written during a panic attack." },

  // A few extra general ones to round it out
  { user: "this should be simple", ai: "Famous last words before 47 edge cases and a 3-day rabbit hole." },
  { user: "just add logging", ai: "Ah yes, console.log — the Duct tape, prayer, and therapy of programming." },
  { user: "why is this slow", ai: "Because you told 10 million records to shake hands one by one. Romance takes time." },
  { user: "review my code", ai: "I reviewed it. My eyes need a vacation and my soul needs an exorcist." },
  { user: "it works on my machine", ai: "Congratulations. You’ve achieved the highest level of isolation known to devkind." },
  { user: "quick question", ai: "In dev time, 'quick' means 47 minutes and 3 newly opened tabs about Rust lifetimes." },
  { user: "it’s production ready", ai: "Translation: 'I ran it twice and prayed both times'." },
  { user: "just make it work", ai: "I did. Now it works exactly as badly as your requirements specified." },
];